---
title: "hilbert transformed signals"
author: "Rebecca Holm"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(pomp)
library(foreach)
library(ggplot2)
library(dplyr)
library(tidyr)
library(reshape2)
library(gridExtra)
library(patchwork)
```

```{r}
df <- read.csv("/Users/rebeccaholm/Desktop/MatØk/Speciale/R/Datasets_NEW/Sr/data_186.csv")
```

```{r}
source("/Users/rebeccaholm/Desktop/MatØk/Speciale/TW - Version 2 - Rebecca/0 Utils/Preprocessing - Amplitude Estimation.R")

Y <- df %>% select(no_trend) %>% unlist()
std_Y <- sd(Y) # save for later (if we want absolute concentration)
mean_Y <- mean(Y) # save for later (if we want absolute concentration)
Y <- (Y-mean_Y)/std_Y # standardize signal
df$amplitude <- AmpEstimation(Y) # Estimate varying amplitude
df$Z <- Y/AmpEstimation(Y) # Define normalized signal
```

# plotter med med ggplot

```{r, height = 10, width=10}
p1 <- ggplot(df, aes(x = Elapsed_DIV_Time)) +
  geom_line(aes(y = Y, color = "Raw Signal"), size = 0.8) +
  geom_line(aes(y = amplitude, color = "Amplitude"), size = 0.7) +
  labs(title = " ",
       x = "", y = "", color = "") +
  scale_color_manual(values = c("Raw Signal" = "black", "Amplitude" = "red")) +
  theme_minimal() + 
  theme(legend.position = "bottom", 
        legend.text = element_text(size = 18))

p2 <- ggplot(df, aes(x = Elapsed_DIV_Time)) +
  geom_line(aes(y = Z, color = "Hilbert transformed Signal"), size = 0.8) +
  geom_line(aes(y = AmpEstimation(Z) , color = "Hilbert transformed Amplitude"), size = 0.7) +
  geom_line(aes(y =  amplitude, color = "Amplitude"), size = 0.7) +
  labs(title = " ",
       x = " ", y = " ", color = "") +
  scale_color_manual(values = c("Hilbert transformed Signal" = "black", "Amplitude" = "red","Hilbert transformed Amplitude" = "blue" )) +
  theme_minimal() + 
  theme(legend.position = "bottom", 
        legend.text = element_text(size = 18)) +
    guides(color = guide_legend(ncol = 2))

p1
p2
```


```{r, height = 10, width=10}
ggsave("/Users/rebeccaholm/Desktop/MatØk/Speciale/TW - Version 2 - Rebecca/Plots_NEW/Used for thesis/raw_signal_amplitude.png", p1, width = 8, height = 6, bg="white")

ggsave("/Users/rebeccaholm/Desktop/MatØk/Speciale/TW - Version 2 - Rebecca/Plots_NEW/Used for thesis/hilbert_signal_amplitude.png", p2, width = 8, height = 6, bg="white")

```

