---
title: "Fitting the Time Warping Model"
author: "Lars Reiter Nielsen"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE,fig.width = 8, fig.height = 6)
```

```{r chunk 0}
library(ggplot2)
library(gridExtra)
library(reshape2)
library(dplyr)

# Source files
source("0 Utils/HelperFunctions.R")
source("0 Utils/Filter - SMC.R")
source("0 Utils/Initialization.R")
source("0 Utils/Estimation.R")
```

## Estimation

```{r chunk 1}
# READ DATA
df <- read.csv("Signal_Synthetic.csv") # Synthetic data
#df <- read.csv("Signal_Real.csv") # Real data

## NOTE: Uncomment below 2 lines if "Synthetic data"
#df <- df[df$piece == unique(df$piece)[1],] # Select first piece
#df$x <- 1:nrow(df)

Y <- df$Y # Y assumed centered and without trend
x <- df$x
delta <- x[2] - x[1]
```

```{r chunk 2}
# (1) FIT TIME WARPING MODEL
fit <- warp.alg(Y, delta)

# (2) PLOT
Bx.fit <- fit$Bx.c
xi.fit <- fit$xi.obj$xi.c

data_fit <- data.frame(x = x, Y = Y)
data_fit$fit_xi <- fit$xi.obj$xi.c
data_fit$fit_gxi <- g(xi.fit,delta)
data_fit$fit_Y <- f(xi.fit, Bx.fit, delta, fit$A.c, fit$b.c)
data_fit$aplusb <- fit$A.c + Bx.fit
data_fit$minusb <- -Bx.fit

# Plot 2.1: fitted signal
p1 <- ggplot(data_fit, aes(x = x)) +
  geom_line(aes(y = Y), color = "black", size = 1) +
  geom_line(aes(y = fit_Y), color = "blue", size = 1, alpha=I(0.9)) +
  geom_vline(xintercept = x[fit$xkstar], color = "red", linetype = "dashed", size=0.7) +
  labs(x = "time (units)", y = "") +
  theme_minimal()

# Plot 2.2: fitted xi
p2 <- ggplot(data_fit, aes(x = x)) +
  geom_line(aes(y = fit_xi), color = "blue", size = 1, alpha=I(0.6)) +
  geom_vline(xintercept = x[fit$xkstar], color = "red", linetype = "dashed", size=0.7) +
  labs(x = "time (units)", y = "") +
  theme_minimal()

# Plot 2.3: fitted g(xi)
p3 <- ggplot(data_fit, aes(x = x)) +
  geom_line(aes(y = fit_gxi + fit$b.c), color = "blue", size = 1,alpha=I(0.9)) +
  geom_vline(xintercept = x[fit$xkstar], color = "red", linetype = "dashed", size=0.7) +
  labs(x = "time (units)", y = "") +
  theme_minimal()

# Plot 2.4: fitted signal + envelope
p4 <- ggplot(data_fit, aes(x = x)) +
  geom_line(aes(y = Y), color = "black", size = 1) +
  geom_line(aes(y = fit_Y), color = "blue", size = 1, alpha=I(0.9)) +
  geom_line(aes(y = aplusb), color = "red", size = 1, alpha=I(0.9)) +
  geom_line(aes(y = minusb), color = "red", size = 1, alpha=I(0.9)) +
  labs(x = "time (units)", y = "") +
  theme_minimal()

grid.plots = grid.arrange(p1,p2,p3,p4,ncol=2)
```

