---
title: "plots"
author: "Rebecca Holm"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("/Users/rebeccaholm/Desktop/MatØk/Speciale/TW - Version 2 - Rebecca/0 Utils/Preprocessing - Amplitude Estimation.R")
library(pomp)
library(foreach)
library(ggplot2)
library(dplyr)
library(tidyr)
library(reshape2)
```



# Henter data ind, så jeg kan få Elapsed_time
```{r}
Sr_210151 <- read.csv("/Users/rebeccaholm/Desktop/MatØk/Speciale/R/Datasets_NEW/Sr/data_210151.csv")
Ba_210151 <- read.csv("/Users/rebeccaholm/Desktop/MatØk/Speciale/R/Datasets_NEW/Ba/data_210151.csv")
Pb_210151 <- read.csv("/Users/rebeccaholm/Desktop/MatØk/Speciale/R/Datasets_NEW/Pb/data_210151.csv")
```

# Henter data ind, så jeg kan få Y og g
```{r}
warp.obj_Sr_210151 <- readRDS("/Users/rebeccaholm/Desktop/MatØk/Speciale/TW - Version 2 - Rebecca/Plots_NEW/Sr/210151/210151_warp_obj_saved.rds")
warp.obj_Ba_210151 <- readRDS("/Users/rebeccaholm/Desktop/MatØk/Speciale/TW - Version 2 - Rebecca/Plots_NEW/Ba/210151/210151_warp_obj_saved.rds")
warp.obj_Pb_210151 <- readRDS("/Users/rebeccaholm/Desktop/MatØk/Speciale/TW - Version 2 - Rebecca/Plots_NEW/Pb/210151/210151_warp_obj_saved.rds")
warp.obj_merged_210151 <- readRDS("/Users/rebeccaholm/Desktop/MatØk/Speciale/TW - Version 2 - Rebecca/Plots_NEW/merged/210151/210151_warp_obj_saved.rds")
```


# Individuelle dataframes for hvert element, så jeg kan styre at hvis Ba har fået fjernet 10 punkter i starten, så starter g-linjen 10 punkter senere på x-aksen 
```{r}
df_Sr_210151 <- data.frame(
                    Elapsed_Time = Sr_210151$Elapsed_DIV_Time,
                    Y = warp.obj_Sr_210151$Y,
                    gx_hat = warp.obj_Sr_210151$gx.hat / (2 * pi),
                    Element = "Sr")

df_Ba_210151 <- data.frame(
                    Elapsed_Time = Ba_210151$Elapsed_DIV_Time,
                    Y = warp.obj_Ba_210151$Y,
                    gx_hat = warp.obj_Ba_210151$gx.hat / (2 * pi),
                    Element = "Ba")

df_Pb_210151 <- data.frame(
                    Elapsed_Time = Pb_210151$Elapsed_DIV_Time,
                    Y = warp.obj_Pb_210151$Y,
                    gx_hat = warp.obj_Pb_210151$gx.hat / (2 * pi),
                    Element = "Pb")

# Create a named list of time vectors
time_vectors <- list(
  Pb = Pb_210151$Elapsed_DIV_Time,
  Sr = Sr_210151$Elapsed_DIV_Time,
  Ba = Ba_210151$Elapsed_DIV_Time
)

# Find the name of the longest one
longest_element <- names(which.max(sapply(time_vectors, length)))

# Extract the longest time vector
Elapsed_Time_longest <- time_vectors[[longest_element]]

# Create the merged data frame
df_merged_210151 <- data.frame(
                        Elapsed_Time = Elapsed_Time_longest,
                        Y = warp.obj_merged_210151$Y,
                        gx_hat = warp.obj_merged_210151$gx.hat / (2 * pi),
                        gx_hat_RAW = warp.obj_merged_210151$gx.hat,
                        Element = "Combined Signal")
```


```{r}
df_all <- bind_rows(df_Sr_210151, df_Ba_210151, df_Pb_210151, df_merged_210151)
```


```{r}
counted_age <- 17

ggplot(df_merged_210151, aes(x = Elapsed_Time, y = gx_hat, color = Element)) +
  geom_line(size = 0.7) +
  geom_hline(yintercept = counted_age, linetype = "dashed", color = "grey30", size = 0.6) +
  annotate("text", x = max(df_all$Elapsed_Time) * 0.3, y = counted_age+0.5,
           label = paste("Counted age = ", counted_age), hjust = 1, color = "grey30", size = 3.5) +
  labs(title = "",
       x = "Elapsed Time", y = "Years") +
  scale_color_manual(values = c(
    # "Ba"     = "#F8766D",
    # "Pb"     = "#00BA38",
    # "Sr"     = "#619CFF",
    "Combined Signal" = "#C77CFF"
  )) +
  theme_bw(base_size = 12) +
  theme_bw() + guides(color = guide_legend(title = NULL))
# + theme(legend.position = "none")
```


```{r}
ggsave("/Users/rebeccaholm/Desktop/MatØk/Speciale/TW - Version 2 - Rebecca/Plots_NEW/used for thesis/combined_growth_time_whale_210151.png", width = 8, height = 5, dpi = 300)
```



# g-plot with data labels
```{r}
counted_age <- 17


df_labels <- df_all %>%
  group_by(Element) %>%
  filter(Elapsed_Time == max(Elapsed_Time)) %>%
  ungroup()


# Create label positions: get the last point for each element for whale 210151
df_labels <- df_labels %>%
  mutate(
    y_offset = case_when(
      Element == "Ba" ~ gx_hat + 0.3,   # nudge up
      Element == "Combined Signal" ~ gx_hat - 0.3,   # nudge down
      TRUE ~ gx_hat                    # leave unchanged
    )
  )



ggplot(df_all, aes(x = Elapsed_Time, y = gx_hat, color = Element)) +
  geom_line(size = 0.7) +
  geom_hline(yintercept = counted_age, linetype = "dashed", color = "black", size = 0.6) +
  annotate("text", x = max(df_all$Elapsed_Time) * 0.3, y = counted_age+0.9,
           label = paste("Counted age = ", counted_age), hjust = 1, color = "black", size = 3.5) +
  geom_text(data = df_labels, aes(y = y_offset, label = sprintf("%.2f", gx_hat)), hjust = -0.1, size = 3.4, show.legend = FALSE) +
  labs(title = "",
       x = "Elapsed Time", y = "Years") +
  scale_color_manual(values = c(
    "Ba"     = "#F8766D",
    "Pb"     = "#00BA38",
    "Sr"     = "#619CFF",
    "Combined Signal" = "#C77CFF"
  )) +
  theme_bw(base_size = 12) +
  xlim(NA, max(df_all$Elapsed_Time) * 1.06) +  # Give space for the label on the right
  guides(color = guide_legend(title = NULL))

ggsave("/Users/rebeccaholm/Desktop/MatØk/Speciale/TW - Version 2 - Rebecca/Plots_NEW/Used for thesis/growth_time_whale_210151.png", width = 8, height = 5, dpi = 300)
```



# old plots
```{r}
ggplot(df_all, aes(x = Elapsed_Time, y = gx_hat, color = Element)) +
  geom_line(size = 0.7) +
  labs(title = "Growth-time process for whale 210151",
       x = "Elapsed Time", y = "Years") +
  theme_bw()


ggplot(df_all, aes(x = Elapsed_Time, y = gx_hat, color = Element)) +
  geom_line(size = 0.7) +
  geom_hline(yintercept = 9, linetype = "dashed", color = "darkgray", size = 0.6) +
  labs(title = "Growth-time process for whale 210151",
       x = "Elapsed Time", y = "Years") +
  scale_color_manual(values = c(
    "Ba"     = "#F8766D",
    "Pb"     = "#00BA38",
    "Sr"     = "#619CFF",
    "merged" = "#C77CFF"
  )) +
  theme_bw()
```


# ############# Time warping plots #####################

Time of death for 21015101 whales is 20210151 and the others are 1986
```{r}
df_merged_210151$time_warp <- 1986 - (max(df_merged_210151$gx_hat_RAW) -df_merged_210151$gx_hat_RAW)/(2*pi)
```

```{r}
ggplot(df_merged_210151, aes(x = time_warp, y = Y)) +
  geom_line(color = "black", size = 0.6) +
  labs(title = "", x = "Years", y = "") +
   scale_x_continuous(breaks = seq(1972, 1986, by = 1)) +
  theme_bw()
```


```{r}
ggsave("/Users/rebeccaholm/Desktop/MatØk/Speciale/TW - Version 2 - Rebecca/Plots_NEW/Used for thesis/time_warped_210151.png", width = 8, height = 5, dpi = 300)
```






