---
title: "Initial_new_data"
author: "Rebecca Holm"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#read in packages
```{r}
library(ggplot2)
library(gridExtra)
library(reshape2)
library(dplyr)
```


# Reading in each sheet as a seperate dataset
```{r}
library(readxl)
```


```{r, results='hide'}
file_path_1 <- "~/Desktop/MatØk/Speciale/Original elemental data from GEUS/Samples_210127_210161_210169_210174_210163_210106.xlsx"  

sheet_names_1 <- excel_sheets(file_path_1)

for (sheet in sheet_names_1) {
  assign(sheet, read_excel(file_path_1, sheet = sheet), envir = .GlobalEnv)
}
```

```{r}
file_path_2 <- "~/Desktop/MatØk/Speciale/Original elemental data from GEUS/Samples_210158_210113_210122_210172_210110_210124_210101.xlsx"  

sheet_names_2 <- excel_sheets(file_path_2)

for (sheet in sheet_names_2) {
  assign(sheet, read_excel(file_path_2, sheet = sheet), envir = .GlobalEnv)
}
```

```{r}
file_path_3 <- "~/Desktop/MatØk/Speciale/Original elemental data from GEUS/Samples_1986008_15_21_100_102_112_133_121_18_127.xlsx"  

sheet_names_3 <- excel_sheets(file_path_3)

for (sheet in sheet_names_3) {
  assign(sheet, read_excel(file_path_3, sheet = sheet), envir = .GlobalEnv)
}
```

```{r}
file_path_4 <- "~/Desktop/MatØk/Speciale/Original elemental data from GEUS/Samples_1986008_26_99_135_157_137_146_164_169_215.xlsx"  

sheet_names_4 <- excel_sheets(file_path_4)

for (sheet in sheet_names_4) {
  assign(sheet, read_excel(file_path_4, sheet = sheet), envir = .GlobalEnv)
}
```

```{r}
file_path_5 <- "~/Desktop/MatØk/Speciale/Original elemental data from GEUS/Samples_1986008-186_188_210129_210125_210111_210149_210114_210160_210151.xlsx"  

sheet_names_5 <- excel_sheets(file_path_5)

for (sheet in sheet_names_5) {
  assign(sheet, read_excel(file_path_5, sheet = sheet), envir = .GlobalEnv)
}
```

```{r}
list <- c(sheet_names_1, sheet_names_2, sheet_names_3, sheet_names_4, sheet_names_5)
```

#Renaming each dataset
```{r}
SMP_210127 <- `SMP - 210127`  
SMP_210161 <- `SMP - 210161`  
SMP_210169 <- `SMP - 210169`  
SMP_210174 <- `SMP - 210174`  
SMP_210163 <- `SMP - 210163`  
SMP_210106 <- `SMP - 210106`  
SMP_510158 <- `SMP - 510158`  
SMP_210113 <- `SMP - 210113`  
SMP_210122 <- `SMP - 210122`  
SMP_210172 <- `SMP - 210172`  
SMP_210110 <- `SMP - 210110`  
SMP_210124 <- `SMP - 210124`  
SMP_210101 <- `SMP - 210101`  
SMP_210129 <- `SMP - 210129`  
SMP_210125 <- `SMP - 210125`  
SMP_210111 <- `SMP - 210111`  
SMP_210149 <- `SMP - 210149`  
SMP_210114 <- `SMP - 210114`  
SMP_210160 <- `SMP - 210160`  
SMP_210151 <- `SMP - 210151`  
SMP_15 <- `SMP - 1986008_15`  
SMP_21 <- `SMP - 1986008_21`  
SMP_100 <- `SMP - 1986008_100`  
SMP_102 <- `SMP - 1986008_102`  
SMP_112 <- `SMP - 1986008_112`  
SMP_121 <- `SMP - 1986008_121`  
SMP_133 <- `SMP - 1986008_133`  
SMP_18 <- `SMP - 1986008_18`  
SMP_127 <- `SMP - 1986008_127`  
SMP_26 <- `SMP - 1986008_26`  
SMP_99 <- `SMP - 1986008_99`  
SMP_135 <- `SMP - 1986008_135`  
SMP_157 <- `SMP - 1986008_157`  
SMP_137 <- `SMP - 1986008_137`  
SMP_146 <- `SMP - 1986008_146`  
SMP_164 <- `SMP - 1986008_164`  
SMP_169 <- `SMP -  1986008_169`  
SMP_215 <- `SMP - 1986008_215`  
SMP_186 <- `SMP - 1986008_186`  
SMP_188 <- `SMP - 1986008_188`  
```



#Manually processing the data for one dataset as a test
```{r}
SMP_169 <- SMP_169 %>%
  setNames(make.names(as.character(SMP_169[1, ]), unique= TRUE))  %>% slice(-1)


SMP_169 <- SMP_169 %>%
  mutate(whale_index = "SMP_169") %>%
  relocate(whale_index, .before = everything())

```


# doing it for all the datasets
```{r}
datasets <- c(
  "SMP_210127", "SMP_210161", "SMP_210169", "SMP_210174", "SMP_210163", 
  "SMP_210106", "SMP_510158", "SMP_210113", "SMP_210122", "SMP_210172", 
  "SMP_210110", "SMP_210124", "SMP_210101", "SMP_210129", "SMP_210125", 
  "SMP_210111", "SMP_210149", "SMP_210114", "SMP_210160", "SMP_210151", 
  "SMP_15", "SMP_21", "SMP_100", "SMP_102", "SMP_112", "SMP_121", 
  "SMP_133", "SMP_18", "SMP_127", "SMP_26", "SMP_99", "SMP_135", 
  "SMP_157", "SMP_137", "SMP_146", "SMP_164", "SMP_169", "SMP_215", 
  "SMP_186", "SMP_188"
)

for (dataset in datasets) {
  assign(dataset, get(dataset) %>%
    setNames(make.names(as.character(get(dataset)[1, ]), unique = TRUE)) %>%
    slice(-1) %>%
    mutate(whale_index = dataset) %>%
    relocate(whale_index, .before = everything()))
}

```

# merging them all togehter 
```{r}
merged_data <- bind_rows(lapply(datasets, get))

print(merged_data)

```

```{r}
merged_data %>% count(whale_index)
```


#removing the . in the column names and replacing with _DIV_ for divided by 
```{r}
merged_data_NEW <-merged_data 
colnames(merged_data_NEW) <- gsub("\\.", "_DIV_", colnames(merged_data_NEW))  # Replaces periods with underscores
```


# Exporting
```{r}
write.csv(merged_data_NEW, "merged_data_NEW.csv", row.names = FALSE)
```


# ####################### Now I will do the plots ####################### 
```{r, fig.width= 2, fig.height=2}
data_filtered <- merged_data_NEW %>% filter(whale_index == "SMP_210127")

data_filtered$Sr_DIV_Ca


# adding artificial x-axis rep. mm 
plot_data <- data_filtered %>%
  mutate(mm_position = seq(0, 500, length.out = n())) %>%
  relocate(mm_position, .before = everything())

# Generate the plot
ggplot(plot_data, aes(x = mm_position, y = Sr_DIV_Ca)) +
  geom_point() +  
  labs(x = "Position (mm)", y = "Sr_DIV_Ca")   # Axis labels

```


